//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TChessGUI.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDI_ICON1                       128
#define IDR_MAINFRAME                   129
#define IDR_TChessGUITYPE               130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDD_ROOT_DIALOG_VIEW            310
#define IDC_COMBO_WHITE_SELECT          1000
#define IDC_COMBO_BLACK_SELECT          1001
#define IDC_BUTTON1                     1002
#define IDC_START_GAME_BUTTON           1002
#define ID_PLAY_STARTNEWGAME            32771
#define ID_SETTINGS_ENGINEDIFFICULTY    32772
#define ID_ENGINEDIFFICULTY_DEPTH2      32773
#define ID_ENGINEDIFFICULTY_DEPTH3      32774
#define ID_ENGINEDIFFICULTY_DEPTH4      32775
#define ID_ENGINEDIFFICULTY_DEPTH5      32776
#define ID_ENGINEDIFFICULTY_DEPTH6      32777
#define ID_HELP_HOWTOSTARTAGAME         32778
#define ID_HELP_HOWTOMAKEAMOVE          32779
#define ID_HELP_ABOUTTCHESS             32780
#define ID_GAME_SAVEGAMETOFILE          32781
#define ID_SAVEGAMETOFILE_CURRENTSTATE  32782
#define ID_SAVEGAMETOFILE_SAVEFULLGAME  32783
#define ID_SOURCE_VIEWCODEONGITHUB      32784
#define ID_SOURCE_VIEWCONSOLEVERSIONONGITHUB 32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
